add_test( MachineInt.Subtest_1 [==[/home/max/work_area/finite-state-machine/laboratory work/cmake_dir/MyMachine]==] [==[--gtest_filter=MachineInt.Subtest_1]==] --gtest_also_run_disabled_tests)
set_tests_properties( MachineInt.Subtest_1 PROPERTIES WORKING_DIRECTORY [==[/home/max/work_area/finite-state-machine/laboratory work/cmake_dir]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MachineInt.Subtest_2 [==[/home/max/work_area/finite-state-machine/laboratory work/cmake_dir/MyMachine]==] [==[--gtest_filter=MachineInt.Subtest_2]==] --gtest_also_run_disabled_tests)
set_tests_properties( MachineInt.Subtest_2 PROPERTIES WORKING_DIRECTORY [==[/home/max/work_area/finite-state-machine/laboratory work/cmake_dir]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MachineChar.Subtest_1 [==[/home/max/work_area/finite-state-machine/laboratory work/cmake_dir/MyMachine]==] [==[--gtest_filter=MachineChar.Subtest_1]==] --gtest_also_run_disabled_tests)
set_tests_properties( MachineChar.Subtest_1 PROPERTIES WORKING_DIRECTORY [==[/home/max/work_area/finite-state-machine/laboratory work/cmake_dir]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MachineStr.Subtest_1 [==[/home/max/work_area/finite-state-machine/laboratory work/cmake_dir/MyMachine]==] [==[--gtest_filter=MachineStr.Subtest_1]==] --gtest_also_run_disabled_tests)
set_tests_properties( MachineStr.Subtest_1 PROPERTIES WORKING_DIRECTORY [==[/home/max/work_area/finite-state-machine/laboratory work/cmake_dir]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( MyMachine_TESTS MachineInt.Subtest_1 MachineInt.Subtest_2 MachineChar.Subtest_1 MachineStr.Subtest_1)
